# Don't print a new line at the start of the prompt
add_newline = false

[character]
success_symbol = "➜"
error_symbol = "✗"

[directory]
truncation_length = 2
read_only = ''

[container]
disabled=true

[line_break]
disabled=true

[cmd_duration]
disabled=true

[c]
disabled=true

[cmake]
disabled=true

[dotnet]
disabled=true

[golang]
disabled=true

[package]
disabled=true

[python]
disabled=true

[rust]
disabled=true

prompt_order=["hostname","directory","git_branch","git state","git_status","jobs"]
