# Don't print a new line at the start of the prompt
add_newline = false

[character]
success_symbol = "➜"
error_symbol = "✗"

[line_break]
disabled=true

[cmd_duration]
disabled=true

[cmake]
disabled=true

[golang]
disabled=true

[python]
disabled=true

prompt_order=["hostname","directory","git_branch","git state","git_status","jobs"]
