#!/bin/bash

# let's update first
sudo apt-get update

# "standards"

sudo apt-get install git
sudo apt-get install openssh-server
sudo apt-get install shellcheck
sudo apt-get install vim
sudo apt-get install htop
sudo apt-get install lldb

# pony dependencies

sudo apt-get install -y build-essential zlib1g-dev libncurses5-dev libssl-dev libpcre2-dev llvm-3.9

###
# DE setup - KDE + i3
#

sudo apt-get install kubuntu-desktop i3-wm wmctrl rofi

#
# end DE setup
###

###
# fish shell
#

if ! test -f /usr/bin/fish
then
  sudo apt-add-repository ppa:fish-shell/release-2
  sudo apt-get update
  sudo apt-get install fish
fi

#
# end fish shell
###

###
# vim modules
#

# line number goodness
if ! test -d ~/.vim/pack/numbers/start/numbers
then
  git clone https://github.com/b3niup/numbers.vim.git ~/.vim/pack/numbers/start/numbers
fi

# pony support
if ! test -d ~/.vim/pack/pony-vim-syntax/start/pony-vim-syntax
then
  git clone https://github.com/dleonard0/pony-vim-syntax.git ~/.vim/pack/pony-vim-syntax/start/pony-vim-syntax
fi

#
#
##

###
# powerline-go
#

if ! test -f ~/bin/powerline-go
then
  pushd /tmp || exit
  wget https://github.com/bketelsen/powerline-go/releases/download/v2.0.3/powerline-go_2.0.3_linux_amd64.tar.gz
  tar xzf powerline-go_2.0.3_linux_amd64.tar.gz
  mv powerline-go ~/bin/powerline-go
  chmod a+x ~/bin/powerline-go
  popd || exit

  sudo apt-get install fonts-powerline
fi

#
# end powerline-go
###

###
# git-lfs
#

curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash

#
# end git-lfs
###

###
# hugo
#

if ! test -f ~/bin/hugo-53 
then
  pushd /tmp || exit
  wget https://github.com/gohugoio/hugo/releases/download/v0.53/hugo_0.53_Linux-64bit.tar.gz
  tar xzf hugo_0.53_Linux-64bit.tar.gz
  mv hugo ~/bin/hugo-53
  chmod a+x ~/bin/hugo-53
  ln -s ~/bin/hugo-53 ~/bin/hugo
  popd || exit
fi

#
# end hugo
###

###
# Exuberant ctags
#

if ! test =f ~/bin/ctags
then
  pushd /tmp || exit
  wget http://prdownloads.sourceforge.net/ctags/ctags-5.8.tar.gz
  tar xzf ctags-5.8.tar.gz
  pushd ctags-5.8 || exit
  ./configure --prefix=$HOME/
  make
  make install
  popd || exit
  popd || exit
fi

#
# end Exuberant ctags
###

###
# 
# CONFIGURATION

sudo chsh -s /usr/bin/fish sean

# END CONFIGURATION
#
###
