#!/bin/bash

# let's update first
sudo apt-get update

# "standards"

sudo apt-get install openssh-server
sudo apt-get install shellcheck
sudo apt-get install vim
sudo apt-get install htop

###
# fish shell
#

sudo apt-add-repository ppa:fish-shell/release-2
sudo apt-get update
sudo apt-get install fish

#
# end fish shell
###

###
# powerline-go
#

echo "Installing powerline-go"

powerline_binary=powerline-go-linux-amd64

pushd /tmp || exit
wget "https://github.com/justjanne/powerline-go/releases/download/v1.11.0/$powerline_binary"
mv "$powerline_binary" ~/bin/powerline-go
chmod a+x ~/bin/powerline-go
popd || exit

sudo apt-get install fonts-powerline

#
# end powerline-go
###

###
# git-lfs
#

curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash

#
# end git-lfs
###

###
# brave browser
#

curl -s https://brave-browser-apt-release.s3.brave.com/brave-core.asc | sudo apt-key add -

source /etc/os-release

echo "deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ $UBUNTU_CODENAME main" | sudo tee /etc/apt/sources.list.d/brave-browser-release-${UBUNTU_CODENAME}.list

sudo apt update

sudo apt install brave-browser brave-keyring

#
# end brave browser
###


###
# 
# CONFIGURATION

sudo chsh -s /usr/bin/fish sean

# END CONFIGURATION
#
###
