theme = "darcula-solid"

[editor]
bufferline = "always"
true-color = true
rulers = [80]
line-number = "absolute"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true
wrap-at-text-width = true
