[[language]]
name = "ponylang"
language-servers = [ "pony-lsp" ]
indent = { tab-width = 2, unit = "  " }

[language-server.pony-lsp]
command = "pony-lsp"

[[language]]
name = "markdown"
scope = "source.markdown"
injection-regex = "md"
file-types = ["md", "markdown"]

[[language]]
name = "starlark"
file-types = ["bzl", "BUILD", "WORKSPACE"]

[[language]]
name = "fish"
auto-format = false
